let nombre = "Lucía";
let apellido = "Gangi";
let estudiante = nombre + " " + apellido;
let estudianteMayus = estudiante.toUpperCase();
let estudianteMinus = estudiante.toLowerCase();
let numLetrasEstudiante = estudiante.length;
let primeraLetraNombre = nombre[0];
let ultimaLetraApellido = apellido[apellido.length - 1];
let estudianteSinEspacios = estudiante.replace(/ /g, "");
